version: '3'
# Before running this, make sure you create the docker network via this command:
# docker network create --driver=bridge --subnet=192.192.0.0/16 --gateway=192.192.0.1 metadatanet
services:
  metadata:
    build: ./builds/metadata
    ports:
      - "28443:443"
      - "28080:80"
    networks:
      metadatanet:
        ipv4_address: 192.192.0.5
    volumes:
      - ./metadata-dev:/siteroot
  metadata-db:
    image: postgres
    networks:
      metadatanet:
        ipv4_address: 192.192.0.3
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: moodle
      POSTGRES_USER: moodle_user
    volumes: 
      - 'metadatadb:/var/lib/postgresql'
  metadata-test-db:
    image: postgres
    networks:
      metadatanet:
        ipv4_address: 192.192.0.4
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: moodle
      POSTGRES_USER: moodle_user
    volumes: 
      - 'metadatatestdb:/var/lib/postgresql'
  # metadata-redis:
  #   build: ./redis
  #   networks:
  #     metadatanet:
  #       ipv4_address: 192.192.0.8
  #   restart: always
  #   volumes:
  #     - 'coreredis:/data'
  # simplesamlphp:
  #   build: ./saml
  #   networks:
  #     moodlenet:
  #       ipv4_address: 192.192.0.2
  #   volumes:
  #     - ./saml:/saml
  # mongodb:
  #   image: mongo:latest
  #   networks:
  #     metadatanet:
  #       ipv4_address: 192.192.0.6
volumes:
    metadatadb:
    metadatatestdb:
networks:
  metadatanet:
    external: true