version: '3'
# Before running this, make sure you create the docker network via this command:
# docker network create --driver=bridge --subnet=192.174.0.0/16 --gateway=192.174.0.1 corenet
services:
  moodle-core:
    build: ./moodle_35
    ports:
      - "28443:443"
      - "28080:80"
    networks:
      corenet:
        ipv4_address: 192.174.0.5
    volumes:
      - ./moodle-master:/siteroot
  core-db:
    image: postgres
    ports:
      - "25432:5432"
    networks:
      corenet:
        ipv4_address: 192.174.0.3
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: moodle
      POSTGRES_USER: moodle_user
    volumes: 
      - 'coredb:/var/lib/postgresql'
  core-test-db:
    image: postgres
    ports:
      - "25433:5432"
    networks:
      corenet:
        ipv4_address: 192.174.0.4
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: moodle
      POSTGRES_USER: moodle_user
    volumes: 
      - 'coretestdb:/var/lib/postgresql'
  # core-integration-db:
  #   image: postgres
  #   ports:
  #     - "25434:5432"
  #   networks:
  #     corenet:
  #       ipv4_address: 192.174.0.7
  #   restart: always
  #   environment:
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_DB: dev_integration
  #     POSTGRES_USER: dev_integration
  #   volumes: 
  #     - 'monashintegrationdb:/var/lib/postgresql'
  # core-redis:
  #   build: ./redis
  #   ports:
  #     - "26379:6379"
  #   networks:
  #     corenet:
  #       ipv4_address: 192.174.0.8
  #   restart: always
  #   volumes:
  #     - 'coreredis:/data'
  # simplesamlphp:
  #   build: ./saml
  #   ports:
  #     - "27443:7443"
  #   networks:
  #     moodlenet:
  #       ipv4_address: 192.174.0.2
  #   volumes:
  #     - ./saml:/saml
  # mongodb:
  #   image: mongo:latest
  #   ports:
  #     - "22701:27017"
  #   networks:
  #     corenet:
  #       ipv4_address: 192.174.0.6
volumes:
    coredb:
    coretestdb:
    # monashintegrationdb:
    # monashredis:
networks:
  corenet:
    external: true