version: '3'
# Before running this, make sure you create the docker network via this command:
# docker network create --driver=bridge --subnet=192.172.0.0/16 --gateway=192.172.0.1 moodlenet
services:
  moodle:
    build: ./moodle_35
    ports:
      - "8443:8443"
      - "8080:8080"
    networks:
      moodlenet:
        ipv4_address: 192.172.0.5
    volumes:
      - ./moodle-master:/siteroot
  moodle-db:
    image: postgres
    ports:
      - "5432:5432"
    networks:
      moodlenet:
        ipv4_address: 192.172.0.3
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: moodle
      POSTGRES_USER: moodle_user
    volumes: 
      - 'moodledb:/var/lib/postgresql'
  moodle-test-db:
    image: postgres
    ports:
      - "5433:5432"
    networks:
      moodlenet:
        ipv4_address: 192.172.0.4
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: moodle
      POSTGRES_USER: moodle_user
    volumes: 
      - 'moodletestdb:/var/lib/postgresql'
  # simplesamlphp:
  #   build: ./saml
  #   ports:
  #     - "7443:7443"
  #   networks:
  #     moodlenet:
  #       ipv4_address: 192.172.0.2
  #   volumes:
  #     - ./saml:/saml
  # mongodb:
  #   image: mongo:latest
  #   ports:
  #     - "2701:27017"
  #   networks:
  #     moodlenet:
  #       ipv4_address: 192.172.0.6
    
volumes:
    moodledb:
    moodletestdb:
networks:
  moodlenet:
    external: true