version: '3'
# Before running this, make sure you create the docker network via this command:
# docker network create --driver=bridge --subnet=192.193.0.0/16 --gateway=192.193.0.1 metadata37net
services:
  metadata37:
    build: ./builds/metadata-37
    ports:
      - "60043:443"
      - "60080:80"
    networks:
      metadata37net:
        ipv4_address: 192.193.0.5
    volumes:
      - ./metadata37-dev:/siteroot
  metadata37-db:
    image: postgres
    networks:
      metadata37net:
        ipv4_address: 192.193.0.3
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: moodle
      POSTGRES_USER: moodle_user
    volumes: 
      - 'metadata37db:/var/lib/postgresql'
  metadata37-test-db:
    image: postgres
    networks:
      metadata37net:
        ipv4_address: 192.193.0.4
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: moodle
      POSTGRES_USER: moodle_user
    volumes: 
      - 'metadata37testdb:/var/lib/postgresql'
  # metadata37-redis:
  #   build: ./redis
  #   networks:
  #     metadata37net:
  #       ipv4_address: 192.193.0.8
  #   restart: always
  #   volumes:
  #     - 'coreredis:/data'
  # simplesamlphp:
  #   build: ./saml
  #   networks:
  #     moodlenet:
  #       ipv4_address: 192.193.0.2
  #   volumes:
  #     - ./saml:/saml
  # mongodb:
  #   image: mongo:latest
  #   networks:
  #     metadata37net:
  #       ipv4_address: 192.193.0.6
volumes:
    metadata37db:
    metadata37testdb:
networks:
  metadata37net:
    external: true