version: '3'
# Before running this, make sure you create the docker network via this command:
# docker network create --driver=bridge --subnet=192.172.0.0/16 --gateway=192.172.0.1 moodlenet
services:
  monash:
    build: ./moodle_35
    ports:
      - "18443:8443"
      - "18080:8080"
    networks:
      monashnet:
        ipv4_address: 192.173.0.5
    volumes:
      - ./monash-siteroot:/siteroot
  monash-db:
    image: postgres
    ports:
      - "15432:5432"
    networks:
      monashnet:
        ipv4_address: 192.173.0.3
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: moodle
      POSTGRES_USER: moodle_user
    volumes: 
      - 'monashdb:/var/lib/postgresql'
  monash-test-db:
    image: postgres
    ports:
      - "15433:5432"
    networks:
      monashnet:
        ipv4_address: 192.173.0.4
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: moodle
      POSTGRES_USER: moodle_user
    volumes: 
      - 'monashtestdb:/var/lib/postgresql'
  monash-integration-db:
    image: postgres
    ports:
      - "15434:5432"
    networks:
      monashnet:
        ipv4_address: 192.173.0.7
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dev_integration
      POSTGRES_USER: dev_integration
    volumes: 
      - 'monashintegrationdb:/var/lib/postgresql'
  # simplesamlphp:
  #   build: ./saml
  #   ports:
  #     - "17443:7443"
  #   networks:
  #     moodlenet:
  #       ipv4_address: 192.173.0.2
  #   volumes:
  #     - ./saml:/saml
  # mongodb:
  #   image: mongo:latest
  #   ports:
  #     - "12701:27017"
  #   networks:
  #     moodlenet:
  #       ipv4_address: 192.173.0.6
volumes:
    monashdb:
    monashtestdb:
    monashintegrationdb: 
networks:
  monashnet:
    external: true